vsim -c -do "do ../scripts/sim.do"
vsim -c -do "do ../scripts/sim.do sim 1"
vsim -c -do "do ../scripts/sim.do sim 2"
vsim -c -do "do ../scripts/sim.do sim 3"
vsim -c -do "do ../scripts/sim.do sim 4"
vsim -c -do "do ../scripts/sim.do sim 5"
vsim -c -do "do ../scripts/sim.do sim 6"
vsim -c -do "do ../scripts/sim.do sim 7"
vsim -c -do "do ../scripts/sim.do sim 8"
vsim -c -do "do ../scripts/sim.do sim 9"
vsim -c -do "do ../scripts/sim.do sim 10"
vsim -c -do "do ../scripts/sim.do sim 11"
vsim -c -do "do ../scripts/sim.do sim 12"
vsim -c -do "do ../scripts/sim.do sim 13"
vsim -c -do "do ../scripts/sim.do sim 14"
vsim -c -do "do ../scripts/sim.do sim 15"
